sudo: required

language: python

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip curl
  - curl -OL https://releases.hashicorp.com/packer/1.3.1/packer_1.3.1_linux_amd64.zip
  - sudo unzip packer_1.3.1_linux_amd64.zip -d "/usr/local/bin/"
  - packer
