language: minimal

services: docker

env:
  - VERSION=1.0

before_script:
  - cd "$VERSION"

script:
  - DOCKER_BUILDKIT=1 docker build --build-arg VERSION="v1.0.0" --build-arg FUSERA_RELEASE="v0.0.17" --build-arg SAMTOOLS_RELEASE="1.9" --build-arg BCFTOOLS_RELEASE="1.9" --build-arg HTSLIB_RELEASE="1.9" . --no-cache

after_script:
  - docker images
